/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newapp;
import java.awt.Color;
import java.util.Locale;
import javax.swing.UIManager;
import java.awt.Image;
import java.awt.Color;
import java.io.File;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


/**
 *
 * @author Subhransu das
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        show(position);
        int trash=doctors();
        Dashboard dd1=new Dashboard();
        int r = dd1.userProfile();
        if (r == 1) {
            jButton17.setVisible(false);
            jButton18.setVisible(true);
            jButton19.setVisible(true);
            jLabel28.setIcon(dd1.jLabel2.getIcon());
        jLabel25.setText(dd1.jLabel3.getText());
        jLabel24.setIcon(dd1.jLabel2.getIcon());
        jLabel27.setText(dd1.jLabel3.getText());
        }
        
    }
    int position=1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel26 = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(250, 250));
        setPreferredSize(new java.awt.Dimension(880, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBackground(new java.awt.Color(100, 158, 234));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel26.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 170, 20));

        jLabel28.setBackground(new java.awt.Color(100, 158, 234));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staticFiles/images/default_profile_pic_50.png"))); // NOI18N
        jLabel28.setOpaque(true);
        jPanel26.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 50, 40));

        jLabel27.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel27.setText("user name");
        jPanel26.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staticFiles/images/keyboard-left-arrow-button (1).png"))); // NOI18N
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel26.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 30, 30));

        jButton17.setText("Login");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel26.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, -1));

        jButton18.setText("logout");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel26.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, -1));

        jButton19.setText("Dashboard");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel26.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, -1));
        jButton19.setVisible(false);

        getContentPane().add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 200, 220));
        jPanel26.setVisible(false);

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setText("EXIT");
        jLabel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel25.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 30));

        jLabel23.setText("Save (CTRL +S)");
        jLabel23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel25.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 30));

        getContentPane().add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 200, 170));
        jPanel25.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(89, 147, 223));
        jLabel1.setText("DOC's");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 60));

        jLabel21.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(89, 147, 223));
        jLabel21.setText("Home");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 40, 30));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staticFiles/images/default_profile_pic_50.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 50, 40));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staticFiles/images/down-chevron.png"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 30, 20));

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel25.setText("user name");
        jPanel27.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 20));

        jPanel1.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 220, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 60));

        jScrollPane1.setBorder(null);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane1.setAutoscrolls(true);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel14MouseMoved(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staticFiles/images/icons8_Back_48px.png"))); // NOI18N
        jLabel30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel30MousePressed(evt);
            }
        });
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 30, 70));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staticFiles/images/icons8_Forward_48px.png"))); // NOI18N
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel31MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel31MouseReleased(evt);
            }
        });
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 20, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backround_1.jpeg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(500, 228));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 772, 218));

        jPanel14.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 870, 250));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cancer Doctors");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 560, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 760, 50));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Image 1");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 80));

        jButton1.setText("Appointment");
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 30));

        jButton2.setText("View");
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Overview");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 60));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 10));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 280));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Image 1");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 80));

        jButton3.setText("View");
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 30));

        jButton4.setText("Appointment");
        jPanel8.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Overview");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 60));
        jPanel8.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 10));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 140, 280));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Image 1");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 80));

        jButton5.setText("View");
        jPanel10.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 30));

        jButton6.setText("Appointment");
        jPanel10.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Overview");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 60));
        jPanel10.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 10));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 140, 280));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Image 1");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 80));

        jButton7.setText("View");
        jPanel12.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 30));

        jButton8.setText("Appointment");
        jPanel12.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Overview");
        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 60));
        jPanel12.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 10));

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 140, 280));

        jPanel14.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 780, 350));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Heart Doctors");
        jPanel16.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 560, 40));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 760, 50));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel18.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 130, 90));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 90));

        jButton9.setBackground(new java.awt.Color(226, 137, 126));
        jButton9.setText("Appointment");
        jButton9.setBorderPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 30));

        jButton10.setText("View");
        jPanel17.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Overview");
        jPanel17.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 60));
        jPanel17.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 10));

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 280));

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Image 1");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel17)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel17)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 80));

        jButton13.setText("View");
        jPanel21.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 30));

        jButton14.setText("Appointment");
        jPanel21.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Overview");
        jPanel21.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 60));
        jPanel21.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 10));

        jPanel15.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 140, 280));

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Image 1");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel19)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel19)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 80));

        jButton15.setText("View");
        jPanel23.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 30));

        jButton16.setText("Appointment");
        jPanel23.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Overview");
        jPanel23.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 60));
        jPanel23.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 10));

        jPanel15.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 140, 280));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 780, 350));

        jScrollPane1.setViewportView(jPanel14);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 880, 860));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // databases();
    
    public ImageIcon takeimage( int i)
    {
//        File f=new File(getClass().getResource("/staticFiles/images/").getFile());
////        File f = new File(getClass().getResource("/newapp/image").getFile());
//        String[] Images=f.list();
        
        userDao d1 = new userDao();
        
           
        d1.Connect();
        banner b1 = new banner();
        Connection conn = d1.conn;
        
        try {

            String myquery = "select * from banner where ID=?";
            PreparedStatement pst = conn.prepareStatement(myquery);

            pst.setInt(1,i);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                b1.img = rs.getBytes("IMAGE");
                ImageIcon image = new ImageIcon(b1.img);
                return image;
//                Image im = image.getImage();
//                Image myImg = im.getScaledInstance(jLabel24.getWidth(),jLabel24.getHeight(), Image.SCALE_SMOOTH);
//                ImageIcon newImage = new ImageIcon(myImg);
//                jLabel24.setIcon(newImage);
//                jLabel28.setIcon(newImage);

            } else {
                System.out.println("invalid image");
 
            }
            pst.close();
            conn.close();
      

        } catch (Exception e) {
            System.out.println(e);
        }
       
        return null;

        
//        System.out.println(f);
//        System.out.println(Images);
//        return Images;
    }
    public void show(int index)
    {
       
            ImageIcon Images=takeimage(index);
            Image image=Images.getImage().getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(),Image.SCALE_SMOOTH);
            jLabel2.setIcon(new ImageIcon(image));
            System.out.println(index);
        
        
//        String img=Images[index];
//        ImageIcon icon=new ImageIcon(getClass().getResource("/staticFiles/images/"+img));
        
        
        
        
    }
    
    
    public int doctors()
    {
        userDao d1=new userDao();
        d1.Connect();
        int fetchd=1;
        Doctors D1=d1.getDoctors(fetchd);
        int did=D1.did;
       
        jLabel14.setText(D1.dname);
        return did;
    }
    
    public int logout() {
        userDao d1 = new userDao();
        d1.Connect();
        Connection conn = d1.conn;
        try {
            String myquery = "update users set status=? where status=?";
            System.out.println(myquery);
            User u1 = new User();

            PreparedStatement pst = conn.prepareStatement(myquery);
            pst.setString(1, "false");
            pst.setString(2, "true");

            int count = pst.executeUpdate();  //inserting data
            System.out.println("number of rows effected:" + count);
            pst.close();
            conn.close();
            return 1;

        } catch (Exception c) {
            System.out.println(c);
            return 0;
        }

    }

//    public int userProfile() {
//        userDao d1 = new userDao();
////        Dashboard dd1=new Dashboard();
//           
//        d1.Connect();
//        User u1 = new User();
//        Connection conn = d1.conn;
//        String contact;
//        try {
//
//            String myquery = "select * from users where status=?";
//            PreparedStatement pst = conn.prepareStatement(myquery);
//
//            pst.setString(1, "true");
//            ResultSet rs = pst.executeQuery();
//
//            if (rs.next()) {
//                System.out.println("successfull");
//                jLabel25.setText(rs.getString(3));
//                jLabel27.setText(rs.getString(3));
//                contact=rs.getString(6);
////                dd1.jLabel11.setText();
////                new Dashboard().jLabel11.setText(rs.getString(6));
//                System.out.println(contact);
//                u1.img = rs.getBytes("IMAGE");
//                ImageIcon image = new ImageIcon(u1.img);
//                Image im = image.getImage();
//                Image myImg = im.getScaledInstance(jLabel24.getWidth(),jLabel24.getHeight(), Image.SCALE_SMOOTH);
//                ImageIcon newImage = new ImageIcon(myImg);
//                jLabel24.setIcon(newImage);
//                jLabel28.setIcon(newImage);
//
//            } else {
//                System.out.println("invalid password or username");
//                return 0;
//            }
//            pst.close();
//            conn.close();
//            return 1;
//
//        } catch (Exception e) {
//            System.out.println(e);
//        }
//        return 0;
//    }
    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setBackground(Color.yellow);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
        jLabel1.setBackground(Color.yellow);
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
        // TODO add your handling code here:
        jPanel2.setBackground(Color.GREEN);

    }//GEN-LAST:event_jPanel2MouseMoved

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        jPanel2.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jPanel14MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseMoved
        // TODO add your handling code here:
        jPanel2.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanel14MouseMoved

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int d=doctors();
       
        Appointment A=new Appointment();
//        new Appointment().setVisible(true);
        A.doctor(d);
        A.setVisible(true);
        this.setVisible(false);

//Resize The ImageIcon

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered

        jPanel25.setVisible(true);
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        jPanel25.setVisible(false);
    }//GEN-LAST:event_jLabel21MouseExited

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        jPanel26.setVisible(true);
//        userProfile pf=new userProfile();
//        jLabel25.setText(pf.uname);
        jPanel27.setVisible(false);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        new Login().setVisible(true);

        this.setVisible(false);
//        userProfile pf=new userProfile();
//        if(pf!=null)
//        {
//            System.out.println(pf.uname);
//            System.out.println(pf.upass);
//           jLabel25.setText(pf.uname);
//           jLabel27.setText(pf.uname); 
//        }
//        else
//        {
//            System.out.println("null");
//        }

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        jPanel26.setVisible(true);
        jPanel27.setVisible(false);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        int r = logout();
        if (r == 1) {
            jButton18.setVisible(false);
            jButton19.setVisible(false);
            jLabel25.setText("user name");
            jLabel27.setText("user name");
            jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staticFiles/images/default_profile_pic_50.png")));
            jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staticFiles/images/default_profile_pic_50.png")));
            jButton17.setVisible(true);

        }

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
       new Dashboard().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jLabel31MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseReleased
              // wrongly i clicked here
    }//GEN-LAST:event_jLabel31MouseReleased

    private void jLabel31MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MousePressed
         new Thread();
        try {
            Thread.sleep(300);
        } catch (InterruptedException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        int p=this.jLabel2.getX();
        System.out.println(p);
        if(p>=1)
        {
//            Animation.Animation.mover_izquierda();
            Animacion.Animacion.mover_izquierda(900,50,1,2,jLabel2);
//            Animacion.Animacion.mover_izquierda(WIDTH, p, ERROR, WIDTH, rootPane);
        }
        position+=1;
//        if(position>5)
//        {
//            position-=1;
//        }
        if(position==4)
        {
            position=1;
        }
//        if(position>=takeimage().length)
//        {
//            position=takeimage().length-1;
//        }
        show(position);
    }//GEN-LAST:event_jLabel31MousePressed

    private void jLabel30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MousePressed
       
        new Thread();
        try {
            Thread.sleep(300);
        } catch (InterruptedException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        int p=this.jLabel2.getX();
        System.out.println(p);
        if(p>=1)
        {
            Animacion.Animacion.subir(900,50,1,2,jLabel2);   // interesting animation
            Animacion.Animacion.mover_izquierda(900,50,1,2,jLabel2);
//            Animacion.Animacion.mover_derecha(900,50,1,2,jLabel2);
           // Animacion.Animacion.subir(900,50,1,2,jLabel2);   // interesting animation

        }
        position-=1;

        if(position<=0)
        {
            position=3;
        }

        show(position);
    }//GEN-LAST:event_jLabel30MousePressed

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {
        jPanel26.setVisible(false);
        jPanel27.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new home().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}

class userProfile {

    public byte[] img;
    public String uname;
    public String upass;
}
